### ISSUE TITLE
请更新oss.sonatype. https://oss.sonatype.org/content/repositories/snapshots/org/fnlp/

### ISSUE THREAD

**Issue by yiakwy** [xpqiu/fnlp#27]
我确认在org/子路径下，并无fnlp包。但是该包却可以被在oss引擎里查询得到。希望尽快修复次bug

**Comment by xpqiu** [comment]
不好意思，回复晚了。因为我只上传了core部分，需要整个项目上传吗？

**Comment by yiakwy** [comment]
需要吧。我只是会稍后用来测试下中文训练情况

2015-12-09 23:56 GMT-05:00 Xipeng Qiu <notifications@github.com>:

**Comment by CodingLionDargon** [comment]
按照QuickTutorial（链接https://github.com/xpqiu/fnlp/wiki/quicktutorial）中的步骤编译工程，在测试分词（命令 java -Xmx1024m -Dfile.encoding=UTF-8 -classpath "fnlp-core/target/fnlp-core-2.1-SNAPSHOT.jar:libs/trove4j-3.0.3.jar:libs/commons-cli-1.2.jar" org.fnlp.nlp.cn.tag.CWSTagger -s models/seg.m "自然语言是人类交流和思维的主要工具，是人类智慧的结晶。"）的时候提醒"找不到或无法加载主类 org.fnlp.nlp.cn.tag.CWSTagger "。

使用Eclipse测试分词时报异常：
java.io.FileNotFoundException: ..\tmp\ar-train.txt (系统找不到指定的路径。)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(Unknown Source)
	at org.fnlp.data.reader.SimpleFileReader.init(SimpleFileReader.java:100)
	at org.fnlp.data.reader.SimpleFileReader.<init>(SimpleFileReader.java:90)
	at org.fnlp.nlp.cn.anaphora.train.ARClassifier.train(ARClassifier.java:144)
	at org.fnlp.nlp.cn.anaphora.train.ARClassifier.main(ARClassifier.java:75)
Exception in thread "main" java.lang.NullPointerException
	at org.fnlp.data.reader.SimpleFileReader.hasNext(SimpleFileReader.java:116)
	at org.fnlp.ml.types.InstanceSet.loadThruStagePipes(InstanceSet.java:214)
	at org.fnlp.nlp.cn.anaphora.train.ARClassifier.train(ARClassifier.java:144)
	at org.fnlp.nlp.cn.anaphora.train.ARClassifier.main(ARClassifier.java:75)
